openapi: "3.0.3"
info:
  title: "MyRent API"
  version: "1.0.0"
  description: "API for MyRent application"
servers:
  - url: "http://localhost:8080"
    description: "Development server"
paths:
  /:
    get:
      summary: "Root endpoint"
      responses:
        '200':
          description: "Successful response"
          content:
            text/plain:
              schema:
                type: string
  /seed-database:
    get:
      summary: "Seed the database"
      responses:
        '200':
          description: "Database seeded successfully"
        '500':
          description: "Error seeding database"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT